import ReactDOM from 'react-dom';
import React from 'react';
import Root from './containers/Root';
import './css/app.css';
import './css/components.css';
import './css/RatingStars.css';
import './css/ContentView.css';
import './css/ProjectView.css';
import './css/ProfileView.css';
import './css/CommentBox.css';
import './css/DeveloperProfileView.css';
import './css/GithubAccountTag.css';
import './css/SSHKeyTag.css';
import './css/NothingHere.css';
import './css/MainHeader.css';
import './css/DetailsPanel.css';
import './css/Comment.css';
import './css/ItemHeader.css';
import './css/StatusHeader.css';
import './css/StatusPanel.css';
import './css/CodeField.css';
import './css/Talent.css';
import './css/SortOptions.css';
import './css/ModalDialog.css';
import './css/InfoHeader.css';
import './css/SearchBar.css';
import './css/Contract.css';
import './css/Review.css';
import './css/WorkStatus.css';
import './css/ProjectSelectionView.css';
import './css/DropdownMenu.css';
import './css/CheckboxList.css';
import 'rc-tooltip/assets/bootstrap.css';
import './css/Tooltip.css';
import './css/WalkthroughMask.css';
import './css/WalkthroughStep.css';
import './css/ListTitleBar.css';
import './css/ListView.css';
import './css/SingleView.css';
import './css/ListElement.css';
import './css/ProfilePicture.css';

ReactDOM.render(<Root />, document.getElementById('react-app'));
