import ReactDOM from 'react-dom';
import React from 'react';
import App from './containers/App';
import './css/app.css';
import './css/components.css';
import './css/RatingStars.css';
import './css/ContentView.css';
import './css/ProjectView.css';
import './css/ProfileView.css';
import './css/CommentBox.css';
import './css/DeveloperProfileView.css';
import './css/GithubAccountTag.css';
import './css/NothingHere.css';
import './css/MainHeader.css';
import './css/DetailsPanel.css';
import './css/Comment.css';
import './css/ItemHeader.css';
import './css/ContractStatusHeader.css';
import './css/StatusPanel.css';
import './css/CodeField.css';

ReactDOM.render(<App/>, document.getElementById('react-app'));
