var keyMirror = require('keymirror');

module.exports = keyMirror({
    LOGIN: null,
    LOGOUT: null,
    APPROVE_NOMINATION: null,
    AUTHENTICATE_GITHUB: null,
    GET_TICKET_DATA: null,
    GET_AUCTION_DATA: null,
    GET_CONTRACT_DATA: null,
    GET_TALENT_DATA: null,
    GET_REVIEW_DATA: null,
    SELECT_VIEW: null,
    SELECT_ROLE: null,
    SELECT_AUCTION: null,
    SELECT_TICKET: null,
    SELECT_CONTRACT: null,
    SELECT_REVIEW: null,
    GET_COMMENT_DETAIL: null,
    GET_USER_DETAIL: null,
    BID_ON_AUCTION: null,
    COMMENT_ON_TICKET: null,
    ADD_COMMENT_TO_AUCTION: null,
    ADD_COMMENT_TO_TICKET: null,
    ADD_COMMENT_TO_REVIEW: null,
    SUBMIT_WORK: null,
    DISPUTE_WORK: null,
    MARK_WORK_COMPLETE: null,
    MARK_WORK_BLOCKED: null,
    MARK_WORK_UNBLOCKED: null,
    MARK_MEDIATION_FAILED: null,
    MARK_MEDIATION_PARTIALLY_COMPLETE: null,
    MARK_MEDIATION_COMPLETE: null,
});
